from __future__ import annotations

from datetime import datetime, timezone

from app.agents.orchestrator import AnalysisResult


def render_markdown_report(result: AnalysisResult) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# DataPilot AI -- Analysis Report",
        "",
        f"*Generated {generated_at}*",
        "",
        "## Question",
        "",
        result.question,
        "",
    ]

    if not result.success:
        lines += ["## Status", "", f"**This question could not be answered.** {result.error}", ""]
        return "\n".join(lines)

    lines += ["## Executive Summary", "", result.insight or "(no summary available)", ""]

    if result.metrics:
        lines += ["## Key Metrics", ""]
        for key, value in result.metrics.items():
            lines.append(f"- **{key.replace('_', ' ').title()}:** {value}")
        lines.append("")

    lines += ["## SQL Query", "", "```sql", result.sql or "", "```", ""]

    if result.result_preview:
        lines += ["## Result Preview", ""]
        cols = list(result.result_preview[0].keys())
        lines.append("| " + " | ".join(cols) + " |")
        lines.append("| " + " | ".join(["---"] * len(cols)) + " |")
        for row in result.result_preview[:10]:
            lines.append("| " + " | ".join(str(row[c]) for c in cols) + " |")
        lines.append("")

    if result.data_quality_warnings:
        lines += ["## Data Quality Warnings", ""]
        for w in result.data_quality_warnings:
            lines.append(f"- **[{w.severity.upper()}]** {w.message}")
        lines.append("")

    if result.follow_up_questions:
        lines += ["## Suggested Follow-up Questions", ""]
        for q in result.follow_up_questions:
            lines.append(f"- {q}")
        lines.append("")

    lines += ["---", "*Report generated by DataPilot AI. Verify results before making business decisions.*"]
    return "\n".join(lines)
